version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: sync_db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./backend/db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_LIST: doc_sync
  #zookeeper:
  #  image: 'bitnami/zookeeper:latest'
  #  container_name: zookeeper
  #  ports:
  #    - '2181:2181'
  #  environment:
  #    - ALLOW_ANONYMOUS_LOGIN=yes

  #kafka:
  #  image: 'bitnami/kafka:latest'
  #  container_name: kafka
  #  ports:
  #    - '9092:9092'
  #    - '9093:9093'
  #    - '9101:9101'
  #  environment:
  #    - KAFKA_BROKER_ID=1
  #    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #    - ALLOW_PLAINTEXT_LISTENER=yes
  #    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #    - KAFKA_CFG_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer
  #    - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
  #    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #    - JMX_EXPORTER_ENABLE=yes
  #    - JMX_EXPORTER_PORT=9101
  #    - JMX_EXPORTER_CONFIG=/etc/jmx-exporter.yml
  #  depends_on:
  #    - zookeeper
volumes:
  zookeeper_data: {}
  zookeeper_datalog: {}
  kafka_data: {}
